on:
  push:
    branches:
      - master
name: Push Event
jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest
    outputs:
      preid: ${{ steps.setPreid.outputs.preid }}
    steps:
        id : setPreid
        run: echo -e "::set-output name=preid::$(date +'%s')"

  deploy:
    name: Run deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
        run: |
          echo -e "Preid is: ${{ needs.build.outputs.preid }}"