on:
  push:
    branches:
      - master
name: Push Event
jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest
    outputs:
      preid: ${{ steps.setPreid.outputs.preid }}
    steps:
      - uses: actions/checkout@v1
      - name: Set preid
        id : setPreid
        run: |
          echo -e "::set-output name=preid::next-$(date +'%s')-${{ github.sha }}"

  deploy:
    name: Run deploy
    runs-on: ubuntu-latest
    outputs:
      preid: ${{ needs.build.outputs.preid }}
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Get preid
        run: |
          echo -e "Preid is: ${{ needs.build.outputs.preid }}"

  test:
    name: Run tests
    runs-on: ubuntu-latest
    outputs:
      preid: ${{ needs.build.outputs.preid }}
    needs: deploy
    steps:
      - uses: actions/checkout@v1
      - name: Get preid
        run: |
          echo -e "Preid is: ${{ needs.deploy.outputs.preid }}" && exit 1